# Generated by Django 4.0.4 on 2022-06-14 18:47

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('desc', models.TextField(max_length=255)),
                ('body', django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True)),
            ],
        ),
    ]
